/** @type {import('tailwindcss').Config} */
export default {
  darkMode: 'class',
  content: ['./index.html', './src/**/*.{js,jsx}'],
  theme: {
    extend: {
      colors: {
        'secondary-fixed': '#e2dfff',
        'inverse-primary': '#bfc1ff',
        'secondary-fixed-dim': '#c3c0ff',
        'on-tertiary': '#ffffff',
        'surface-bright': '#f8f9ff',
        secondary: '#5451b8',
        'surface-container-highest': '#d3e4fe',
        'on-surface-variant': '#464651',
        'on-surface': '#0b1c30',
        'surface-variant': '#d3e4fe',
        'on-error-container': '#93000a',
        'on-secondary': '#ffffff',
        surface: '#f8f9ff',
        background: '#f8f9ff',
        'on-primary-fixed-variant': '#393d91',
        'on-error': '#ffffff',
        'tertiary-fixed-dim': '#8dcff3',
        'tertiary-fixed': '#c3e8ff',
        'on-tertiary-container': '#488bad',
        'surface-container-lowest': '#ffffff',
        error: '#ba1a1a',
        'surface-tint': '#5156aa',
        'on-primary-fixed': '#070666',
        'on-primary-container': '#777cd3',
        'on-secondary-container': '#29228d',
        'primary-container': '#070666',
        'surface-dim': '#cbdbf5',
        'on-tertiary-fixed-variant': '#004c68',
        'on-tertiary-fixed': '#001e2c',
        'on-primary': '#ffffff',
        'surface-container-high': '#dce9ff',
        'on-secondary-fixed': '#0f0069',
        'tertiary-container': '#001e2c',
        'primary-fixed': '#e1e0ff',
        primary: '#000000',
        tertiary: '#000000',
        'on-secondary-fixed-variant': '#3c379f',
        'surface-container-low': '#eff4ff',
        'secondary-container': '#9592fe',
        outline: '#777683',
        'inverse-on-surface': '#eaf1ff',
        'inverse-surface': '#213145',
        'surface-container': '#e5eeff',
        'on-background': '#0b1c30',
        'primary-fixed-dim': '#bfc1ff',
        'outline-variant': '#c7c5d3',
        'error-container': '#ffdad6',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        full: '9999px',
      },
      spacing: {
        gutter: '1rem',
        'space-md': '1rem',
        margin: '1.5rem',
        'gutter-lg': '1.5rem',
        'margin-compact': '1rem',
        'space-xs': '0.25rem',
        'space-xl': '2rem',
        'space-sm': '0.5rem',
        'space-lg': '1.5rem',
        'space-2xl': '3rem',
        'space-2xs': '0.125rem',
      },
      fontFamily: {
        'data-metric': ['Plus Jakarta Sans'],
        'headline-sm': ['Plus Jakarta Sans'],
        'label-sm': ['Plus Jakarta Sans'],
        'display-md': ['Plus Jakarta Sans'],
        'body-lg': ['Plus Jakarta Sans'],
        'label-md': ['Plus Jakarta Sans'],
        'headline-md': ['Plus Jakarta Sans'],
        'body-md': ['Plus Jakarta Sans'],
        'display-lg': ['Plus Jakarta Sans'],
        'receipt-mono': ['JetBrains Mono'],
        'body-sm': ['Plus Jakarta Sans'],
        'label-lg': ['Plus Jakarta Sans'],
        'headline-lg': ['Plus Jakarta Sans'],
      },
      fontSize: {
        'data-metric': ['28px', { lineHeight: '36px', fontWeight: '700' }],
        'headline-sm': ['16px', { lineHeight: '24px', fontWeight: '600' }],
        'label-sm': ['11px', { lineHeight: '14px', fontWeight: '700' }],
        'display-md': ['24px', { lineHeight: '32px', fontWeight: '700' }],
        'body-lg': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'label-md': ['12px', { lineHeight: '16px', fontWeight: '600' }],
        'headline-md': ['18px', { lineHeight: '26px', fontWeight: '600' }],
        'body-md': ['14px', { lineHeight: '20px', fontWeight: '400' }],
        'display-lg': ['32px', { lineHeight: '40px', fontWeight: '700' }],
        'receipt-mono': ['12px', { lineHeight: '18px', fontWeight: '500' }],
        'body-sm': ['12px', { lineHeight: '16px', fontWeight: '400' }],
        'label-lg': ['14px', { lineHeight: '20px', fontWeight: '600' }],
        'headline-lg': ['20px', { lineHeight: '28px', fontWeight: '600' }],
      },
    },
  },
  plugins: [],
}
